import React from "react";
import type {Metadata} from "next";



export const metadata: Metadata = {
    title: 'Cucurbita',
    description: 'Generated by create next app',
}
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <div>
                {children}
        </div>
    )
}
