import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from "@/components/header";
import Footer from "@/components/footer";
import {Providers} from "@/app/providers";
import { ThemeModeScript } from "flowbite-react";

const poppins = Poppins({ weight: ["100","200","300","400","500","600","700","800","900"], subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Home | Cucurbita',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
      <html lang="en">
      <head>
          <ThemeModeScript/><title></title>
      </head>
      <body className={poppins.className}>
      <Providers>
            <Header/>
          <main className="w-full light bg-background text-foreground overflow-x-hidden">
              {children}
          </main>
            <Footer/>
      </Providers>
      </body>
      </html>
  )
}
